# Intercom redirect, requires special headers
[[redirects]]
  from = "https://support.balance.io/*"
  to = "https://custom.intercom.help"
  status = 200
  force = true
  headers = {Host = "support.balance.io"}
